### ISSUE TITLE
questions about forwarder

### ISSUE THREAD

**Issue by Vad1mo** [digital-wonderland/docker-logstash-forwarder#10]
It seems like https://github.com/progrium/logspout is doing the same as docker-logstash-forwarder
Do you know what is the different in you project compared to progrium/logspout ?

**Comment by digital-wonderland** [comment]
If I'm not mistaken logspout doesn't handle in container logs and allows some configurable routing via a REST API.

**Comment by Vad1mo** [comment]
what do you mean with "logspout doesn't handle in container logs"?
As I understand from reading the docs, this feature is the USP of both projects resulting that one doesn't need to modify each container in order to send logs to logstash. 

Or do you mean logspout can only handle stderr and stdout?

**Comment by digital-wonderland** [comment]
Yes, AFAIK logspout forwards only stderr & stdout for every container but is not able to forward arbitrary other log files, which is why I wrote docker-logstash-forwarder.
