### ISSUE TITLE
vagrant up doesn't run any containers

### ISSUE THREAD

**Issue by aduis** [digital-wonderland/docker-logstash-forwarder#11]
Hey, 

I've tried to run your vagrant machine using vagrant up and unfortunately it doesn't start any containers. Did I forget something? I just started vagrant up (as described in the readme). Would be great to get some help here.

Thanks, 
Andre

**Comment by aduis** [comment]
I think I found a workaround to fix this issue. Just run vagrant reload after vagrant up and all containers are running perfectly. The coreos cloud init only gets executed when you reboot the machine. Maybe put another reboot step to your Vagrantfile. 

But apart from this minot issue this works perfectly. Thanks for this.

**Comment by digital-wonderland** [comment]
Hm, just running ```vagrant up``` should be enough - also I just tried it from scratch and it worked just fine.

During the first start the VM has to download 4 different Docker images, which can take quite some time. My guess would be that it was simply still trying to download things. To verify this, just tail the syslog after ```vagrant up``` (with ```journalctl -f```), which should give some hint what is happening or not.
