### ISSUE TITLE
ca.crt path

### ISSUE THREAD

**Issue by lovrenca** [digital-wonderland/docker-logstash-forwarder#13]
Was just looking at this file to figure out how to handle certificates.
https://github.com/digital-wonderland/docker-logstash-forwarder/blob/master/forwarder/config/config.go

I found this function and was wondering, is it ok, that the SslCa is pointing at the same file as the
SslCertificate?

```
// NewFromDefault returns a new default config.
func NewFromDefault(logstashEndpoint string) *LogstashForwarderConfig {
	network := Network{
		Servers:        strings.Split(logstashEndpoint, ","),
		SslCertificate: "/mnt/logstash-forwarder/logstash-forwarder.crt",
		SslKey:         "/mnt/logstash-forwarder/logstash-forwarder.key",
		SslCa:          "/mnt/logstash-forwarder/logstash-forwarder.crt",
		Timeout:        15,
	}

	config := &LogstashForwarderConfig{
		Network: network,
		Files:   []File{},
	}

	return config
}
```

**Comment by digital-wonderland** [comment]
IIRC this is the result of the entry being required and me wanting to make it work with the least effort.

If you want to use a different configuration, use the ```-config``` flag.

**Comment by lovrenca** [comment]
Thx for info :)
Great image btw :+1:
