### ISSUE TITLE
digitalwonderland/logstash-forwarder doesn't show actual logstash-forwarder logs in 'docker logs'

### ISSUE THREAD

**Issue by berndv** [digital-wonderland/docker-logstash-forwarder#14]
Cannot find any log entry from logstash-forwarder in logs of digitalwonderland/logstash-forwarder.

Cost me half of a day to figure out that my certs were invalid. 

Actual logstash forwarder told me:

```
2015/04/24 14:41:49.132812 Loading client ssl certificate: /etc/sysconfig/logstash-forwarder/lumberjack.crt and /etc/sysconfig/logstash-forwarder/logstash-forwarder.key
2015/04/24 14:41:49.292452 Failed loading client ssl certificate: crypto/tls: private key does not match public key
```

Started docker-logstash-forwarder even with `-debug=true -quiet=false` ... didn't help.

Maybe things get screwed up with #12.

P.S.: Please consider versioned tags when pushing to docker hub...

**Comment by digital-wonderland** [comment]
I'm not sure, if I understand you correctly. If your certificates are invalid, logstash-forwarder can not connect to Logstash and therefore you being unable to find any logs is 'working as expected' (how should those logs get into Logstash?).

The ```-quiet``` flag just gets passed on to logstash-forwarder and makes it 'operate in quiet mode - only emit errors to log' (according to its docs). So, if it can not connect, it should be an error, which should show up even when run with ```-quiet```. If it does not, please raise an issue with the logstash-forwarder folks.

**Comment by stibi** [comment]
Hi, I just got into the same problem :) Wrong certificate…I don't blame the docker-logstash-forwarder, the wrong certificate was my fault. It was just a little bit more complicated to find out what is the actual problem, as I was setting up the ELK stack for first time so I was not sure what is the problematic thing…
Anyway, it works now, thanks a lot for this project, works great and I have logs from my CoreOS cluster consolidated in place, perfect.

**Comment by digital-wonderland** [comment]
I had another look and whenever I tamper with the key or cert logstash-forwarder outputs error messages, even when run with ```-quiet```.

As in I get something like

```
Failed loading client ssl certificate: crypto/tls: private key does not match public key
```
or
```
Failed loading client ssl certificate: crypto/tls: failed to parse private key
```
which shows up in STDOUT and therefore in ```docker logs```, so everything is behaving as expected.

What is currently broken, is that the ```-quiet``` flag has no effect. I opened #15 for this.
