### ISSUE TITLE
-quiet flag has no effect

### ISSUE THREAD

**Issue by digital-wonderland** [digital-wonderland/docker-logstash-forwarder#15]

**Comment by digital-wonderland** [comment]
@tfnico you probably want to update your code / init scripts since the default changed to being verbose.

This is due to Gos flag handling & me thinking that handling ```-quiet``` in the same way as logstash-forwarder is less confusing. Sorry for the trouble.

**Comment by tfnico** [comment]
@digital-wonderland Thanks for the heads up.
