### ISSUE TITLE
/etc/logstash-forwarder.conf ignored with aufs

### ISSUE THREAD

**Issue by ablock84** [digital-wonderland/docker-logstash-forwarder#17]
I'm building a custom docker image where I use ADD to include a custom /etc/logstash-forwarder.conf to the container image. This custom configuration is however ignored as it is not found by NewFromContainer. I tried to understand the code a little bit and it looks like calculateFilePath returns a wrong path. 

Currently calculateFilePath uses /var/lib/docker/aufs/diff/{containerId} as base path, but as I understand the layout of /var/lib/docker/aufs/diff, this directory contains the diff to the container's image but not the image itself. 

A simple test (and currently my workaround) can be performed by simply doing a touch on /etc/logstash-forwarder.conf in the CMD of the Dockerfile, as this causes aufs to copy-on-write the file into /var/lib/docker/aufs/diff/{containerId}

Here is an example Dockerfile that has this problem:
```
FROM jboss/wildfly

ADD logstash-forwarder.conf /etc/logstash-forwarder.conf

CMD /opt/jboss/wildfly/bin/standalone.sh
```

If I simply do a touch before calling the real start command, the /etc/logstash-forwarder.conf is not ignored:

```
CMD touch /etc/logstash-forwarder.conf && /opt/jboss/wildfly/bin/standalone.sh
```

I have the feeling that calculateFilePath should actually go through the containers image and parent images and test for existence of the config file in each of them and return the first found file. I really would like to implement that by myself, but I never did development with Go...

**Comment by digital-wonderland** [comment]
I can not reproduce this. With a Dockerfile as you stated above I end up with the following path:
```
/var/lib/docker/aufs/diff/787bd49a9149944c2ea0b34cdfe1dc8526bcbdc9b50f7a88444781ec40b4e096/etc/logstash-forwarder.conf
```
This is with Ubuntu 15.04 and should be the same with Debian 8. Which OS are you using as Docker host?

Also note that this might be related to #1 (earlier aufs data was bellow ```aufs/mnt``` and now is bellow ```aufs/diff``` - perhaps the behaviour you described was what happened earlier - dunno, I never used something which used the aufs driver except when trying to reproduce some issue here).

**Comment by ablock84** [comment]
For some reason my hotfix also stopped working when deploying to a SLES 12 with a Docker 1.5. I'm going to re-investigate further.

In the meantime I had an idea on how to solve the issue of locating the config for all drivers with a more general solution. As I understand, you have full access to the hosts Docker daemon from inside your container. Can't you do an exec with a simple "cat /etc/logstash-forwarder.conf" on the other containers to retrieve the configuration? It should work on mostly all containers found in the universe...at least I can not imagine that we have too many containers even missing a cat (and busybox).

The log files referenced in the config should not be a problem with that solution as they will always appear in the aufs/diff folder (as processes are writing to them).

**Comment by ablock84** [comment]
Update: Or use docker cp to retrieve the config.

**Comment by digital-wonderland** [comment]
Compared to the current approach this would complicate things quite a bit, which I don't really want to do because it works just fine with a recent version of ```aufs``` and I have neither the personal use case nor the time, so I wont spend any time on this.

Since it is SLES perhaps checking with SuSE support when a newer version of aufs comes along or if another driver can be used might make sense?
