### ISSUE TITLE
Log Rotation 

### ISSUE THREAD

**Issue by Trane9991** [digital-wonderland/docker-logstash-forwarder#19]
Would be nice to add some option to rotate Docker Containers logs. Because restart of docker-logstash-forwarder leads to sending all logs again in one pack.

**Comment by digital-wonderland** [comment]
I think there is some misunderstanding how it works: docker-logstash-forwarder just generates configuration for logstash-forwarder and restarts it if the configuration changes. logstash-forwarder is the only thing which forwards anything anywhere and already handles restarts nicely by storing its positions within log files within the ```.logstash-forwarder``` file.

So the only way how you should end up with log lines getting send multiple times, is when your ```.logstash-forwarder``` file gets lost. To avoid this, you have two options:
* don't delete the docker-logstash-forwarder container (i.e. don't run it with ```--rm``` - would still happen if you update the container).
* use a Docker volume to get your ```.logstash-forwarder``` file stored there and then mount it into your current container.

**Comment by Trane9991** [comment]
Thank you for reply.
