### ISSUE TITLE
Field names cannot contain the . character in Elasticsearch 2.0

### ISSUE THREAD

**Issue by cookandy** [digital-wonderland/docker-logstash-forwarder#20]
Just to let you know, in Logstash 2.x field names cannot contain ```.```

Until the template gets fixed, you can setup a filter on your logstash server to remove the periods

```
filter {
  ruby {
        code => "
          event.to_hash.keys.each { |k| event[ k.sub('.','_') ] = event.remove(k) if k.include?'.' }
        "
    }
}
```

See here https://discuss.elastic.co/t/field-name-cannot-contain/33251/11

**Comment by digital-wonderland** [comment]
Thanks a lot for the heads up. I opened https://github.com/elastic/elasticsearch/issues/14594 to inquire if they intend to change that. If not I'll update the code to use ```_``` instead of ```.```.

**Comment by wallies** [comment]
@digital-wonderland First off, awesome solution for logstash-forwarder. I still get this issue, the problem is when some containers are using things like com.amazonaws.ecs.container-name and works.weave.role as their labels. Should I use the filter above or could you handle it in code?

**Comment by cookandy** [comment]
I am also running into problems for some reason.  Going to reopen this issue.
