### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by dbason** [digital-wonderland/docker-logstash-forwarder#5]
1) Is there any way to define a more complex network section of the logstash-forwarder config?  E.g can we add multiple logstash servers for redundancy and can we define settings like the network time out.

2) Can we define fields to be added to the logstash-forwarder config?  E.g for each container we would want to sent a field with the container name for easy identification.

**Comment by karthik87** [comment]
Does this eliminate the need for SSL keys for communication between the forwarder and the logstash server?

**Comment by digital-wonderland** [comment]
@karthik87 No, logstash-forwarder does all the transport, which requires SSL certificates.

**Comment by fakewaffle** [comment]
How would I add additional custom fields to stdout?

**Comment by fakewaffle** [comment]
Essentially, I need to be abliltiy to provide a config and have it merge with [this](https://github.com/digital-wonderland/docker-logstash-forwarder/blob/ebb7613697f9fa0b396830f4341965d6361ba1b0/forwarder/config/config.go#L40-46).

**Comment by digital-wonderland** [comment]
@fakewaffle unfortunately this is not possible via configuration. What field(s) are you missing?

**Comment by fakewaffle** [comment]
We want to be able to do custom ones that we would set in a file with SaltStack and have merged. The "keys" relate to the host and environment the docker containers are running in.

**Comment by digital-wonderland** [comment]
@fakewaffle that should be possible by using Logstashs _mutate_ filter

**Comment by fakewaffle** [comment]
Is mutate supported with `-config` https://github.com/elastic/logstash-forwarder/blob/master/config.go?

**Comment by digital-wonderland** [comment]
@fakewaffle not sure, what you mean? As _-config_ is supported whatever is a valid _logstash-forwarder_ config, while [_mutate_](https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html) is a _Logstash_ plugin / filter.

FWIW, I just added support for [Docker labels](https://docs.docker.com/userguide/labels-custom-metadata/), which might help you as well.
