### ISSUE TITLE
Custom docker folder

### ISSUE THREAD

**Issue by jwalton** [digital-wonderland/docker-logstash-forwarder#9]
You can change the location of the docker folder from /var/lib/docker to wherever you want by editing /etc/default/docker, and adding:

    DOCKER_OPTS="-g /path/to/docker/data"

It would be nice if this wasn't hard coded [here](https://github.com/digital-wonderland/docker-logstash-forwarder/blob/master/forwarder/config/config.go#L125).  Maybe read from an environment variable to make it easy to set the location?

Cool tool, BTW.  :)

**Comment by digital-wonderland** [comment]
Thanks, not sure if I'm misunderstanding you, but the line you are referring to, is within the containers filesystem.

For example if your docker data is bellow ```/home/foo/.docker```, you must map that into the containers ```/var/lib/docker``` via ```-v /home/foo/.docker:/var/lib/docker``` and it should just work.

Does this help?

**Comment by jwalton** [comment]
This is one of those facepalm moments.  :)
